### ISSUE TITLE
[VC]: Sync Kubernetes PriorityClasses Upward to Virtual Cluster

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/multi-tenancy#1007]
Would there be interest in supporting the syncing of `PriorityClasses` upward from the Supercluster into the virtualcluster since they share the scheduling domain, this could be very similar to how StorageClasses are synced?

/cc @weiling61 @Fei-Guo

**Comment by charleszheng44** [comment]
It's a little different from the StorageClasses, if my memory is correct, in the StorageClass case, an VC can't see PVs on the supercluster, unless it creates a PVC and successfully binds it to a PV on the supercluster. 

However, I think it can be done as long as we assume every VC has the same priority.

**Comment by Fei-Guo** [comment]
Interesting request. Technically, syncing priority class to upper tenant master is doable. In my opinion, PC is not very suitable for multi-tenant cases since if there are no tenant-aware rules and enforcement about how to apply suitable PC name for Pod, one tenant may abuse it and starve the rest of the tenants.

**Comment by christopherhein** [comment]
Yeah, the idea would be if a supercluster exposed X priority classes and tenants were allowed to use them and only them then we be able to sync those to the tenant cluster users for visibility. This does cause the case where some workloads could take precedence and could evict pods running in other priority classes from other tenants but you could envision that somewhat akin to spot instances in AWS where it's just a policy of the system.

If nothing else I'm thinking this could be added as an "optional syncer", maybe we make `--resources=configmap,endpoint,event,namespace,node,persistentvolume,persistentvolumeclaim,pod,secret,service,serviceaccount,storageclass,priorityclass` then when we startup the syncer if we don't want all of them we could pick and choose. 

wdyt?

**Comment by charleszheng44** [comment]
Sounds good to me.

**Comment by Fei-Guo** [comment]
It is ok to put PC as optional resource to sync and I would suggest to treat all existing resources as core resources which cannot be chosen and do --extraresources = priorityclass for new ones. 

IMO, there is a slight difference here that spot instance is related to cost. If we don't have a charging model or proper regulations for using priority class, one tenant can mark all his Pods as high priority ones since no one can judge its validity. It is unfair to tenants that use Priority class correctly then.

**Comment by Fei-Guo** [comment]
Btw, I am not against this proposal.  Since we have put some much effort to avoid interference in VC, I just don't want to easily  expose a way to allow tenant to game the system. Of course, make it optional and default off is fine. It is still better we have some thoughts/solutions in mind to prevent the abuse from happening though.

**Comment by christopherhein** [comment]
Yeah, I 100% agree. It's a little strange and I would love to think of good abstractions to help reduce the likelihood of abuse. this could be very concerning. Have any thoughts on what that could look like? The general idea around priority class in k8s gives such a different level of cluster usage.

**Comment by Fei-Guo** [comment]
Perhaps, we can leverage the idea of Yarn scheduler, it uses an elastic quota and preemption happens within quota range. We actually have submitted a KEP to K8s scheduler to adopt the idea. 

With quota, tenant cannot easily game the system. If alloc + request > quota, the preemption happens to tenant's own pods. Otherwise, the preemption happens to other tenants whose alloc + request > quota.

**Comment by christopherhein** [comment]
Interesting… so this is a good lead on I was about to file another issue regarding syncing `ResourceQuotas` down from a virtualcluster as a way of at least gating some of this but it would still be controlled at the virtualcluster level vs at the super cluster level. IE you could set your own Namespace level ResourceQuotas… from an oversubscription perspective this causes concerns cause you could request larger than the entire cluster at an individual Namespace or at a single VC level which raises concerns.

**Comment by weiling61** [comment]
Another way to prevent tenant to abuse the system is to set price tag or quota to different priority classes they will use. Resource quota system monitors the usage of resources in different priority classes for each namespace/vc, and blocks resource creation if it bypasses allowed quota.

**Comment by christopherhein** [comment]
Yeah, but that ends up being the responsibility of the operator of the system not something we can define as the OSS community :) Everyones operational costs will be different. I think enabling the tools for people to make those decisions is what is going to be the most important.

**Comment by christopherhein** [comment]
/close

this was implemented in the merged PRs
