### ISSUE TITLE
VC: Use VC controller to deploy CoreDNS

### ISSUE THREAD

**Issue by salaxander** [kubernetes-sigs/multi-tenancy#1064]
Since a forked version of CoreDNS is needed in a tenant cluster, @christopherhein and I were discussing if it would make sense to have to VirtualCluster controller allow an option to auto-deploy CoreDNS in tenant clusters. I'm happy to implement this if the group feels it's a good option :)

**Comment by christopherhein** [comment]
Thanks for filing this @salaxander. 

@Fei-Guo because of the way the control plane is currently configured the Control Plane DNS resolving is using the super clusters DNS provider, this makes using tenant local DNS to route to webhooks and admission controllers need to have special hostnames that route across the supercluster namespaces.

The idea here would be that we could have an option at cluster creation to auto-deploy CoreDNS first so that we can then reconfigure the DNS Config for the apiserver to use the per-tenant CoreDNS prior to boot.

**Comment by Fei-Guo** [comment]
@christopherhein @salaxander  

Let us discuss the workflow in more details. If we create DNS pod in super before creating apiserver, then the DNS works for control plane only. The tenant Pod cannot use this DNS because the current contract is that we will put the cluster ip of kube-dns service in tenant kube-system ns to the Pod dns config.
https://github.com/kubernetes-sigs/multi-tenancy/blob/23e6e2489656e0888094810314ae382c5fe0dfcd/incubator/virtualcluster/pkg/syncer/resources/pod/dws.go#L235

One option is that we can have two dns servers, one for control plane, one for tenant Pods. If this seems to be too costly, another hacky workflow can be 
- Install dns inside tenant master as tenant addons in tenant control plane creation workflow 
- Have another script run in tenant apiserver Pod which periodically checks the dns server in tenant apiserver and updates the Pod /etc/resolv.conf to use tenant dns cluster ip if it is available.

**Comment by salaxander** [comment]
I think the best option here would be to install dns as a tenant add-on in the tenant control plane creation. @christopherhein, thoughts?

**Comment by christopherhein** [comment]
Yeah, thinking this through more coredns in k8s needs to have the control plane access in order for it to come up, so we really have a weird chicken and egg problem where if we bring up the control plane first we don’t have tenant local dns to route to for things like admission webhooks or auth webhooks but if you bring up coredns first it’s not going to have a control plane to talk to immediately and thus with crashloopbackoff until the apiserver comes up, I don’t know if that is a bad thing though.

I believe, and correct me if I’m wrong, if we had coredns come up first (even if this was just the Service) we could rewrite the dnsConfig for the control plane pod to use that service in it’s resolve.conf, then the control plane could come up and we could change the syncer to set the dnsConfig for each pod to use the control plane provisioned coredns, even though it would technically be out of the “view” of the tenant control plane user.

Maybe this wouldn’t work?

**Comment by Fei-Guo** [comment]
- This requires to change the syncer to use a super master service (the coredns one) in Pod dnsconfig
- If tenant install coredns again, there is going to be a conflict. 

But if we want to go with this direction, I am ok with the following:
- Check tenant kube-system/kube-dns service first, and use the super `root-ns-XXX-kube-system/kube-dns` service cluster ip in dnsConfig
- If the above service does not exist, additionally check super `root-ns/kube-dns` service cluster ip in dnsConfig.
- else go default.
