### ISSUE TITLE
VC: Support VC CR specifying the Control Plane Namespace Name

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/multi-tenancy#1073]
This is open for discussion, but would it make sense to allow the `VirtualCluster` CR to have a field for `spec.clusterNamespace` something that it could use provision the tenant control plane into? What issues would this cause? 

Throughout the code base it seems we have a conversion function https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/virtualcluster/pkg/syncer/conversion/helper.go#L52-L55 that will create the control plane namespace name, this is used heavily in the sync controller and I’m assuming elsewhere, it currently takes in the virtual cluster object and will sha256 of the UID and prefix/postfix with the original namespace and cluster name respectively, I’m thinking we could change this to have a generation function if one isn’t specified as well we could then change this to return the value stored in `status.clusterNamespace`.

I’m concerned about using the UID field in the namespace because this could be changed as we version the `VirtualCluster` CR for example if we create a v1beta1 and we set that as the stored resource I’m not certain that the UID will stay the same as it gets restored in etcd. This would also allow a virtual cluster user to specify their own scheme for managing cluster namespaces and help reduce the likelihood of control plane namespace + tenant namespace to extend beyond the Namespace field max length limits that we have to do in https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/virtualcluster/pkg/syncer/conversion/helper.go#L59-L62

wdyt?

**Comment by Fei-Guo** [comment]
Are you suggesting to make `spec.clusterNamespace` as the prefix of generated name? otherwise, it is difficult to resolve ns conflict in super master. 

Note that giving this flexibility will create the chance of ns conflict in super master. Tenant namespace can never be the prefix substring of another tenant namespace ( say tenant A uses "foo" and tenant B uses "foobar", tenant A cannot create ns "bar" in tenant master  ), even though appending random hash string after the ns name can help reducing the chance.

Current way of constructing the tenant ns name in super can maximally reduce the chance of ns conflict. 

Currently, the tenant ns clean up is done asynchronously after vc-object is deleted. We can never assume the same name will not be used by another tenant, then we will have trouble for security. Also, this cannot help ns name limit since it may always happen as we use one ns space quota for two namespaces. 

Overall, the tenant root ns name is very critical in syncer design. I don't think it is a good idea to offer tenant control for this. 

With regard to whether UID is changed after version change, I have done a quick test and found the UID is not changed after changing the version from v1alpha1 to v1beta1.

**Comment by christopherhein** [comment]
Yes, I'm thinking the cluster namespace prefix. I'm assuming that we could technically enforce things like must be a unique namespace prefix using validating admission webhook. 

The criticality in the syncer was my concern as well. The security aspects of not being able to reclaim someone else's NS after they deleted the cluster is a good point. 

Thanks for checking on the UID field. 

Closing this for now.

/close
