### ISSUE TITLE
HNC: Presubmit tests are flaky 

### ISSUE THREAD

**Issue by GinnyJI** [kubernetes-sigs/multi-tenancy#1170]
Logs at https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_multi-tenancy/1161/pull-hnc-test/1313137143345844224

**Comment by GinnyJI** [comment]
Another failure log at https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_multi-tenancy/1169/pull-hnc-test/1313215677913370624

**Comment by adrianludwin** [comment]
/assign @GinnyJI 
Thanks!

**Comment by adrianludwin** [comment]
I just reproduced one of these failures after about 5 attempts by running:

`stress -m 22 -i 36 -c 24`

This command is available via apt-get, and loads of the workstation with a ton of other processes, all chewing through CPU and memory. E.g. my workstation has 12 cores, and this loads it up with 22 memory-hogging processes, 36 IO-hogging processes and 24 CPU-hogging processes. I guessed that the Prow machines are probably heavily overloaded and as a result, we could see some really weird concurrency behaviour we'd never see on our workstations.

Sure enough, the failure I saw in `"should stop propagating objects if a type is first set to propagate mode then removed from the spec"` looks like it could be some weird timing corner case. The test appears to do the following:

1. enable propagation of secrets
2. verify that a secret is propagated
3. disable propagation of secrets
4. wait until HNCConfig reports that secrets are no longer being propagated
5. creates a new secret and verifies that it is not propagated

What's strange is that I see HNC report that secrets are no longer being propagated (step 4) _after_ the new secret is created and (incorrectly) propagated (step 5). Classic concurrency bug.

I believe the problem is that we don't stop and wait between steps 1 and 2 for the HNCConfig to be updated. However, there's a time lag between when the new propagation mode takes effect, and when we write this fact back to the apiserver. I _think_ that we don't successfully manage to write the HNCConfig (which changed in step 1) back to the apiserver until _after_ step 4, which means that step 4 "passes" but actually we should still be waiting.

I'm looking into some of the other failures now to see if there are similar causes.
