### ISSUE TITLE
windows how to use hns within kubectl

### ISSUE THREAD

**Issue by JaneLiuL** [kubernetes-sigs/multi-tenancy#1260]
Windows platform, when I download https://github.com/kubernetes-sigs/multi-tenancy/releases/download/hnc-v0.6.0/kubectl-hns_darwin_amd64 and put on the bin folder,  how to use
Now When I try "kubectl hns tree -A" on windows CMD, will fail said "Error: unknown command "hns" for "kubectl""

**Comment by adrianludwin** [comment]
We don't pre-build Windows executables so the HNS plugin won't work on
Windows. If you have a Go toolchain you should be able to compile it for
yourself and it *should* work, but since none of the HNC developers have
Windows workstations, we're not able to test it ourselves. If you can build
it and it works, we can add it to our release process.

Will you be able to help with that?
Thanks!

**Comment by adrianludwin** [comment]
Moved to https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/22

/close
