### ISSUE TITLE
[HNC] Is it possible for controllers to watch subnamespace resources?

### ISSUE THREAD

**Issue by Jeffwan** [kubernetes-sigs/multi-tenancy#1286]
My org may consider to use HNC to resolve hierarchical namespace challenges. We have some controllers and want to install them in every subnamespace and make sure every user has their own control plane. 

We want deploy controller in every subnamespace and only watch events at subnamespace level. is it impossible?  Seems sub namespace it is backed by Kubernetes namespace. We think it's possible to change controller to watch to the sub namespace?

 kubernetes
  - org A namespace (real namespace)
    - userA namespace (subnamespace)
    - userB namespace (subnamespace)
  - org B namespace (real namespace)

**Comment by adrianludwin** [comment]
That would have to depend on the controller you're installing. I believe
the Go clients *can* set up watches on individual namespaces, and since HNC
subnamespace are simply K8s namespaces, that will work. However, the
controller has to be designed to be configurable so that it can set up the
watch on the correct namespace.

It's not possible to watch a *tree* of namespaces, since trees are HNC-only
concepts while "watching" is a core K8s concept. So in your example, you
*would* be able to put a watch on userA or orgB and it would work the way
you expect. But if you put a watch on orgA, it would *only* watch that one
namespace, and not its subnamespaces. (Technically, the controller could be
upgraded to understand HNC hierarchies and create watches on all descendant
namespaces, but that's only feasible if you own the controller or if the
controller author loves HNC).

Does this make sense?

**Comment by Jeffwan** [comment]
@adrianludwin 

> Technically, the controller could be upgraded to understand HNC hierarchies and create watches on all descendant namespaces, but that's only feasible if you own the controller or if the controller author loves HNC

Got it. That means for most of the controllers, they can only watch leaf node in the hierarch if we don't make extra changes. 

To enable watch for other nodes (namespaces like orgA), we probably can change controller logic to use HNC client to read leafs nodes recursively and filter out all the namespaces under orgA. Then controller can register to watch events of these namespaces. I will try to do some POC for my controllers and report it back. 

To make it generic enough, I think once HNC graduates, it would be great to add these logics to `NewFiltersSharedInformerFactory` and controller will have out-of-box support

**Comment by adrianludwin** [comment]
Assuming the namespace is called "org-a", all namespaces in its tree will
have the "org-a.tree.hnc.x-k8s.io/depth" label present, so that's a good
way of selecting subtrees. There's no need for a recursive search.

Sadly, NewFiltersSharedInformerFactory  doesn't appear to support filtering
by labels today, but this would be a more extensible method of adding
support than direct HNC integration IMO.

**Comment by adrianludwin** [comment]
I'm closing this since it's sadly not feasible today, but if `NewFiltersSharedInformerFactory` adds label filtering we could revisit this. Please ping me again if you'd like to discuss this further!

/close
