### ISSUE TITLE
HNC: document that some E2E tests cannot run with Hierarchy Controller

### ISSUE THREAD

**Issue by GinnyJI** [kubernetes-sigs/multi-tenancy#1295]
Before running E2E test suite, Hierarchy Controller has to be uninstalled first, otherwise any test that needs HNC_REPAIR will cause problems. I don't know if and how we should document this.

**Comment by adrianludwin** [comment]
We already print a big warning if HNC_REPAIR is _not_ set. Maybe if
HNC_REPAIR _is_ set, we need to print a big warning saying "Make sure HNC
isn't being managed by an operator (like ACM or Config Sync) since we're
about to make changes to it!" followed by a 5s delay so that you can ctrl-c
your way out of it?

**Comment by adrianludwin** [comment]
Fixed by #1487
/close
