### ISSUE TITLE
HNC: Provide multiarch images (e.g. arm64)

### ISSUE THREAD

**Issue by DWSR** [kubernetes-sigs/multi-tenancy#1383]
Hey all, I'd like to use HNC with my ARM cluster, but can't because HNC doesn't provide ARM images (that I can see).

Not sure how much work this would be, but would definitely help those of us running on e.g. AWS Graviton or Raspberry Pis.

**Comment by adrianludwin** [comment]
Interesting. I'd love to support ARM but I'm not sure how to create a
multiarch image and (much more importantly) I have no way of testing it
since I don't have access to an ARM cluster.

Are you able to provide a PR and test it on your cluster?

**Comment by DWSR** [comment]
@adrianludwin This is relatively straightforward to build with [buildx](https://medium.com/@artur.klauser/building-multi-architecture-docker-images-with-buildx-27d80f7e2408). I haven't done it with CloudBuild before, but it appears that someone else has: https://hub.docker.com/r/harshavardhanj/docker-buildx. I don't have easy access to a GCP account for CloudBuild, though.

Regarding testing, GCP (and thus GKE) doesn't appear to have any ARM support, so that would be a pretty major change. I'm happy to test it against my home Pi cluster to get an image out the door, but that's obviously not a reasonable approach moving forward.

How are images for e.g. `kube-proxy` and other Control Plane components tested for various architectures?

**Comment by adrianludwin** [comment]
I'm not sure how the other components are tested - most testing is on GCP,
which as you say, only has Intel and AMD support.

I'd be comfortable using a build process that only got tested once, as long
as we stated clearly that this is the case (this is what we do with macOS
support for kubectl-hns). As for Cloud Build, if you sign up for a GCP
account, you get 120 free build-minutes of Cloud Build a day
<https://cloud.google.com/build/pricing> on an e2-medium. That should be
enough to test, since HNC typically builds in well under 5 minutes.

Sorry I don't have the time to look into this myself. I know ARM is getting
more common as a target for GKE so I'm sure someone will get to it at some
point, but right now I don't have the time or ability to look into it. If
you can get something working on your test account I'll be happy to merge
it (after a few questions) but if not, I'm going to have to wait until GCP
customers are asking for it (e.g. Anthos on-prem) or someone else is able
to submit a PR. Sorry about that!

**Comment by adrianludwin** [comment]
This issue has moved to https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/21. Closing this copy.

/close
