### ISSUE TITLE
Feature Request: Support dry run with hns

### ISSUE THREAD

**Issue by vikas027** [kubernetes-sigs/multi-tenancy#1404]
It would be great to have a dry-run feature to get the yaml. My use case is to get the yaml and use it with a GitOps tool like flux or argo.

```bash
❯ kubectl hns create monitoring -n platform --dry-run=client -o yaml
Error: unknown flag: --dry-run
Usage:
  kubectl-hns create -n PARENT CHILD [flags]

Flags:
  -h, --help   help for create

Global Flags:
      --as string                      Username to impersonate for the operation
      --as-group stringArray           Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --cache-dir string               Default HTTP cache directory (default "/Users/vikas/.kube/http-cache")
      --certificate-authority string   Path to a cert file for the certificate authority
      --client-certificate string      Path to a client certificate file for TLS
      --client-key string              Path to a client key file for TLS
      --cluster string                 The name of the kubeconfig cluster to use
      --context string                 The name of the kubeconfig context to use
      --insecure-skip-tls-verify       If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure
      --kubeconfig string              Path to the kubeconfig file to use for CLI requests.
  -n, --namespace string               If present, the namespace scope for this CLI request
      --request-timeout string         The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests. (default "0")
  -s, --server string                  The address and port of the Kubernetes API server
      --tls-server-name string         Server name to use for server certificate validation. If it is not provided, the hostname used to contact the server is used
      --token string                   Bearer token for authentication to the API server
      --user string                    The name of the kubeconfig user to use

unknown flag: --dry-run
~ underwent 463ms
❯ 
```

**Comment by adrianludwin** [comment]
Hmm, I actually didn't know that you could use dry-run to get yaml back like that in other tools. Neat!

With that said, we don't actually recommend the output of `kubectl hns create` for Gitops - that command creates a [subnamespace](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/docs/user-guide/concepts.md#basic-subns), whose main value is that the user does _not_ have permission to create namespaces themselves. Typically, Flux or Argo _will_ have such permissions, so for those tools, we recommend:

- Creating the namespace explicitly using the normal methods
- Creating the hierarchical relationships between the namespaces using `HierarchyConfiguration` objects

A `HierarchyConfiguration` object looks like this:

```
apiVersion: hnc.x-k8s.io/v1alpha2
kind: HierarchyConfiguration
metadata:
  name: hierarchy # this name is mandatory
  namespace: <the child namespace name>
spec:
  parent:  <the parent namespace name>
```

You can also create this object with `kubectl hns set <child> --parent <parent>` but because that only updates one part of the object at a time, I don't think that `--dry-run -oyaml` makes sense for that.

Does this help?

**Comment by vikas027** [comment]
Thanks, @adrianludwin

This definitely helps,  I have just tested this out with ArgoCD works like a charm. Feel free to close the ticket :)

**Comment by adrianludwin** [comment]
Great, thanks!

If you want to submit a docs PR on how to make this work better, maybe
check out
https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/docs/user-guide/best-practices.md#gitops
and see if there's anything you want to add. Any contributions are
appreciated!

/close
