### ISSUE TITLE
HNC: restructure object controller to allow explicit enqueuing

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#195]
The Object controller doesn't allow for manual enqueing; either we can try to update every object of a certain type as a single, serial operation (`SyncNamespace`); if any _one_ fails, we need to redo _all_ of them. By contrast, the HierarchyConfig reconciler allows for individual enqueues and retries of individual failures.

Once we can enqueue a reconcile for a specific object, this unlocks many other improvements such as enqueuing a reconcile for objects that don't yet exist as a batch operation.

**Comment by yiqigao217** [comment]
@rjbez17  Since the new object controller is implemented and tested, can we switch it as the default? We may want to keep the old controller code for the coming performance test. After the performance test is done, we can remove the code. WDYT?

I also manually tested the new object controller on Kind. It behaved just as we expected, e.g. manually-modified propagated objects got overwritten by the controller and got propagated to the newly-added children. In addition, everything worked fine when the controller is manually restarted.

**Comment by rjbez17** [comment]
Yeah I'm all for it. Since we are still pre-aplpha I don't see any reason to do a typical deprecation policy.

**Comment by rjbez17** [comment]
I would be interested in some metrics on the performance differences between the old vs new. I'm also happy to help with that testing, just let me know.
