### ISSUE TITLE
tenancy crd client code

### ISSUE THREAD

**Issue by rkamudhan** [kubernetes-sigs/multi-tenancy#20]
Is there we can upstream the tenant crd client code using https://blog.openshift.com/kubernetes-deep-dive-code-generation-customresources ?

**Comment by srampal** [comment]
That is exactly the plan … for now instead of being fully prescriptive, the plan is to build a few POCs like this one below and then move to the final consensus over the next few months.

https://github.com/kubernetes-sigs/multi-tenancy/tree/master/poc/tenant-controller

Rgds,
Sanjeev

ps. We have a couple of WG sessions on this topic at Kubecon Europe which would be great to for anyone interested to attend and provide your input (in addition to the ongoing biweekly WG meetings).

**Comment by rkamudhan** [comment]
@srampal Thanks Sanjeev. I like contribute on this. Looking forward to collaborate on this effort.

**Comment by srampal** [comment]
I guess this issue can be closed because this work is already happening as noted earlier via the following POC

https://github.com/kubernetes-sigs/multi-tenancy/tree/master/poc/tenant-controller
