### ISSUE TITLE
clarify incubator directory intent

### ISSUE THREAD

**Issue by liggitt** [kubernetes-sigs/multi-tenancy#56]
The readme calls out the `poc` folder as containing explicitly unsupported code. What is the disposition of `incubator` directory? Nesting code inside that folder seems like it will be problematic/disruptive to unnest if those projects persist/grow. Should we move those to the poc folder or move them to their own repos?

**Comment by liggitt** [comment]
cc @adrianludwin @Fei-Guo

**Comment by adrianludwin** [comment]
I think having their own repos would be great - but isn't creating a repo a
fairly heavyweight operation? I think the idea is that things should stay
in the incubator until enough people are using them that it's worth moving
them to their own repo; this means there's churn for those early adopters,
but without adopters, we have a chicken-and-egg problem.

**Comment by Fei-Guo** [comment]
Virtual cluster has almost no dependency with Tenant CRD and other subsystems. In the end it is just a CRD created in tenant admin namespace. Virtual cluster is solely a multi-tenancy solution hence it is suitable for multi-tenancy repo. Since both VC and tenant CRD are in developing phase, it is not clear what the best repo organization should be. Hence "incubator" directory was proposed to be used as a temporal location. Once VC is ready and I show a live demo to sig, sig can decide where it should go.

**Comment by adrianludwin** [comment]
The only problematic question I can see is "which SIG is this." Perhaps it
would be helpful to have an organization *other* than kubernetes-sigs for
incubator projects?
