### ISSUE TITLE
HNC: Ensure no-one puts a finalizer on a HierarchyConfiguration object

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#623]
Currently, `updateFinalizers` (`pkg/reconcilers/hierarchy_config.go`) assumes that any existing finalizer can be removed. This is probably a correct assumption, but we don't have a webhook to prevent anyone else from adding a finalizer to an HC. We should add that.

**Comment by rajibmitra** [comment]
hi @adrianludwin thank you for the starting points, I will work on the test case now.

**Comment by adrianludwin** [comment]
/remove-lifecycle stale

Thanks!

**Comment by yiqigao217** [comment]
To be clear, this is only trying to notify users explicitly that their attempt to add finalizers is not allowed, right? (by having a webhook to deny it).

In reality, users adding the finalizers on the HC object won't cause any issue because the HC reconciler resets the finalizers (either to `nil` or to `hnc.x-k8s.io/hasSubnamespace`) in each reconciliation. This issue is similar to #1494 that we only want to deny it explicitly for users, and even without the new webhook rule, it won't break anything, right? @adrianludwin

**Comment by adrianludwin** [comment]
I didn't realize that, but it sounds reasonable :)

**Comment by adrianludwin** [comment]
Moved to https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/29

/close
