### ISSUE TITLE
HNC: Add proper conditions to Hierarchy status

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#76]
Currently, the [conditions](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/api/v1alpha1/hierarchy_types.go#L68) in the HNC status are simply a set of strings. In addition, conditions don't propagate between namespaces. This is a proposal to make them more structured, machine-readable, and useful.

# Error codes and references

We should expand the `Condition` struct to include the following new fields:

- `code`: a machine-readable string value (values shown below) summarizing the condition.
- `affects`: a list of group-version-kind-namespace-name that uniquely identifies the object(s) affected by the condition.

## Initial list of conditions.

Some condition codes will start with the prefix `CRIT_` which indicates that this is a critical error; until the error is resolved, HNC will no longer make any changes in this namespace (or its descendants).

I would recommend the following _initial_ set of codes (clients should expect that the list can gro over time):

- `CRIT_PARENT_MISSING`: The specified parent is missing.
  - `affected` and `msg` are empty.
- `CRIT_PARENT_INVALID`: The specified parent is invalid (ie would cause a cycle).
  - `affected` is empty and `msg` describes the cycle.
- `CRIT_ANCESTOR`: A critical error exists in an ancestor namespace, so this namespace is no longer being updated.
  - `affected[0].name` identifies the most recent ancestor with a critical condition. `msg` is empty.
- `OBJECT_OVERRIDDEN`: An object in this namespace has been overridden from its parent and will no longer be updated.
  - `affected[x].{group,version,kind,namespace,name}` is set for every such object. `msg` _may_ summarize the errors in a human-readable form.
- `OBJECT_DESCENDANT_OVERRIDDEN`: An object in this namespace is no longer being propagated because a propagated copy has been modified.
  - `affected[x].{group,version,kind,namespace,name}` identifies the modified copy, and `msg` _may_ summarize the errors.
  - Note that `OBJECT_OVERRIDDEN` will be set for the same object in its own namespace
  - This condition should be set in the namespace that contains the source object. If the source is in a grandparent, and the modification is in the child, `DESCENDANT_OVERRIDDEN` will _not_ be set on the intermediate namespace.

## Implementation

`pkg/forest` should be modified to allow for conditions to be quickly set and unset. I _think_ the best way to do it is as follows: `forest.Namespace` gets a new `Conditions map[string][]Code` field. The value (`[]Code`) is a list of typedef'd strings that can take on the values shown above. The key (the string) is one of the following:

- Empty for conditions affecting _this_ namespace (ie `CRIT_PARENT_MISSING`, `CRIT_PARENT_INVALID`, `DESCENDANT_OVERRIDDEN)
- A namespace name if referring to another namespace (ie `CRIT_ANCESTOR`)
- A string of the form `group/version/kind/namespace/name` for the `OBJECT_` conditions.

This format allows the reconciler for any object to easily clear any conditions that it is causing in any other namespace. Then, the namespace reconciler can reassemble the errors into the per-code format shown above.

**Comment by yiqigao217** [comment]
In addition to the set of codes listed above, I think we need to add one more to the initial set after the self-serve is in place:
* CRIT_CONFLICT: there's a conflict between this namespace and another (ie this namespace is in another namespace's RequiredChildren spec, but this namespace has a different Parent spec).
 *affected[0].name identifies the namespace that has a conflict with this one. msg describes the conflict.

**Comment by adrianludwin** [comment]
sgtm although I'd be a bit more verbose than CRIT_CONFLICT - maybe
CRIT_REQUIRED_CHILD_CONFLICT?

**Comment by yiqigao217** [comment]
Sure.

Do you think we can have ```affected``` as empty instead of having ```affected[0].namespace``` (storing the most recent ancestor with CRIT_ conditions) for CRIT_ANCESTOR condition in the Hier object? Since we will check all ancestors instead of trusting the stored values to trace up.

However, when the ```CRIT_``` conditions in the current namespace is resolved, we may need some way to enqueue all children namespaces affected by these ```CRIT_``` conditions?



Currently what I have is as follows:

**Conditions in Hier object:**
* ```CRIT_PARENT_MISSING```: The specified parent is missing.
  * ```affected``` and ```msg``` are empty.
* ```CRIT_PARENT_INVALID```: The specified parent is invalid (ie would cause a cycle).
  * ```affected``` is empty and ```msg``` describes the cycle.
* ```CRIT_REQUIRED_CHILD_CONFLICT```: There's a conflict between this namespace and another (ie this namespace is in another namespace's ```RequiredChildren``` spec, but this namespace has a different ```Parent``` spec).
  * ```affected``` is empty and ```msg``` describes the conflict.
* ```CRIT_ANCESTOR```: A critical error exists in an ancestor namespace, so this namespace is no longer being updated.
  * ```affected``` and ```msg``` are empty.

**Conditions in forest namespace:** the map stores all ```CRIT_``` and ```OBJECT_``` conditions except the ```CRIT_ANCESTOR``` condition. There's no need to store ```CRIT_ANCESTOR``` since it's dependent on ancestors' ```CRIT_``` errors and it will be updated in the Hier object directly.

**Comment by yiqigao217** [comment]
Another thought I had previously is that each time we successfully set/unset(change) a CRIT_ condition in the currently namespace, all its children namespaces should be enqueued, considering they may be set/uset CRIT_ANCESTOR conditions.

In this case, we cannot clear all CRIT_ conditions in the in-memory forest at the beginning of each reconciling and just get new CRIT_ conditions, because we need previous conditions.

**Comment by adrianludwin** [comment]
> Do you think we can have affected as empty instead of having affected[0].namespace (storing the most recent ancestor with CRIT_ conditions) for CRIT_ANCESTOR condition in the Hier object?

This is just for usability - we don't necessarily need to _store_ this in any persistent way, but we should _report_ it to users, I think.

> However, when the CRIT_ conditions in the current namespace is resolved, we may need some way to enqueue all children namespaces affected by these CRIT_ conditions?

I don't understand this question? Your latest commit lgtm so far.

> Another thought I had previously is that each time we successfully set/unset(change) a CRIT_ condition in the currently namespace, all its children namespaces should be enqueued, considering they may be set/uset CRIT_ANCESTOR conditions.

+1

> In this case, we cannot clear all CRIT_ conditions in the in-memory forest at the beginning of each reconciling and just get new CRIT_ conditions, because we need previous conditions.

I think we agreed on fixing this by calling it `ns.ClearLocalConditions()` or `ns.ClearConditions(forest.Local)`

**Comment by yiqigao217** [comment]
> > Do you think we can have affected as empty instead of having affected[0].namespace (storing the most recent ancestor with CRIT_ conditions) for CRIT_ANCESTOR condition in the Hier object?
> 
> This is just for usability - we don't necessarily need to _store_ this in any persistent way, but we should _report_ it to users, I think.
> 
> 
> > Another thought I had previously is that each time we successfully set/unset(change) a CRIT_ condition in the currently namespace, all its children namespaces should be enqueued, considering they may be set/uset CRIT_ANCESTOR conditions.
> 
> +1
> 
> > In this case, we cannot clear all CRIT_ conditions in the in-memory forest at the beginning of each reconciling and just get new CRIT_ conditions, because we need previous conditions.
> 
> I think we agreed on fixing this by calling it `ns.ClearLocalConditions()` or `ns.ClearConditions(forest.Local)`

The implementation of adding ```CRIT_ANCESTOR``` condition mentioned in # 2 and # 3 above are totally different. # 2 is to enqueue/set ```CRIT_ANCESTOR```  condition to all children when ```CRIT_``` conditions in this namespace changed. Basically, the ```CRIT_ANCESTOR```  condition is not set locally but by an ancestor namespace. While # 3 would be setting ```CRIT_ANCESTOR``` locally even without storing it in in-memory forest.

Considering the most recent ancestor namespace with ```CRIT_``` condition is only used for usability mentioned in # 1 (but not used to trace up/down to unset ```CRIT_ANCESTOR``` condition in namespaces), we can just go with the # 3 implementation, right?

Then there will be a problem for the case when an ancestor namespace resolves its ```CRIT_``` conditions. Currently it doesn't reconcile its children. We will need to handle this case by enqueuing all its children, right? Then we will need to compare the old conditions with the new conditions?

**Comment by yiqigao217** [comment]
Based what stated above, the implementation could be:
* store ```CRIT_``` condition before clearing local conditions and compare the difference to see if ```CRIT_``` of this namespace is updated (set/unset) and decide whether to enqueue all children. 
* ```CRIT_ANCESTOR``` is still set locally by looking upwards the ancestors.

**Comment by adrianludwin** [comment]
Discussed offline - agreed that this is the right way to go.

**Comment by yiqigao217** [comment]
Now that all ```CRIT_``` conditions are done, I 'm going to add ```OBJECT_``` conditions.

Here's the implementation in my mind: 
* All the changes will be in ```object_controller.go```
* ```OBJECT_``` conditions will be SET where the src/copy-object-diff is found in ```ensureCorrectAncestry()```. (Do we still keep the ```annotationModified```? Maybe yes, since this is the only mark on object inst.)
* Besides ```ensureCorrectAncestry()``` check before propagation, we will need an additional check (say ```ensureCleanNamespace()```) to see if the object's namespace has ```CRIT_``` conditions. If yes, it will stop the propagation too.

Please correct me if anything looks off.

**Comment by adrianludwin** [comment]
I think we can ditch the `modified` annotation for now - yes, it's the only mark _on_ the object, but I think we should train people to look at `hierarchyconfig.status.conditions` to look for problems, not in other locations. Also, this would mean that if the object is modified, we stop touching it completely, which feels like the right thing to do to me - "you look weird, I'm not touching you anymore."

Stopping propagation when the namespace has a critical condition sgtm, though maybe not as a part of the same PR?

Also, we're locking and unlocking the forest in multiple places right now. That seems vaguely wrong to me - we should probably lock it and unlock it once. However, we shouldn't keep the lock while contacting the apiserver, so we should only consolidate the calls if we can do something like this:

- load a bunch of stuff from the apiserver
- lock; sync with the forest; unlock
- write back to the apiserver

I don't think this is how `update` is structured today, so maybe restructuring it like this might be a good first step?

**Comment by yiqigao217** [comment]
Thanks for sorting through.

Yes, consolidating the calls with forest lock sounds good, since otherwise I will make another separate func with forest lock to get namespace ```CRIT_``` conditions.

So basically, it can be 3 PRs:
* Restructure ```update``` to consolidate calls with forest lock
* Add ```OBJECT_``` conditions
* Check namespace ```CRIT_``` conditions before propagation

**Comment by adrianludwin** [comment]
+1

**Comment by adrianludwin** [comment]
Is this issue finished?

**Comment by yiqigao217** [comment]
Yes for v0.1, since we moved object conditions to v0.2.

In v0.1, only CRIT_ conditions are set. I will clean up (remove) the OBJECT_ condition const and close this issue.
