### ISSUE TITLE
[MTB] implement benchmark lifecycle

### ISSUE THREAD

**Issue by phoenixking25** [kubernetes-sigs/multi-tenancy#792]
Task to run preliminary tests/checks before running benchmarks.
- [ ] Check the given namespace is valid or not.
- [ ] Check the given user/SA is valid or not.
- [ ] Check if there is KubeConfig at $HOME/.kube/config (alternative take kubeconfig from ENV.
- [ ] Check the given user has RBAC privileges to create pods/services/deployments.

**Comment by JimBugwadia** [comment]
@phoenixking25 - please rename to "implement benchmark lifecycle" or close and open a separate issue. As discussed we can add a common `validate` function (may be different per level) and then for each benchmark define the lifecycle phases: 
- validate or Pre-Run: if this returns an error the test is marked as "error" instead of "fail".
- Run: if this returns an error the test is marked as "fail", otherwise "pass".

Not sure if we need a post-run. Thoughts?
