### ISSUE TITLE
HNC: Failed e2e tests right after `make deploy`

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#825]
Since it takes about 30s for the webhook server to be available after deployment, running e2e tests right after `make deploy` will fail (won't be able to create any namespaces because the webhook is fail close). e.g. 
```
Error from server (InternalError): Internal error occurred: failed calling webhook "namespaces.hnc.x-k8s.io": Post https://hnc-webhook-service.hnc-system.svc:443/validate-v1-namespace?timeout=30s: dial tcp 10.110.188.85:443: connect: connection refused
```

It took me a while to figure this out. Here are the steps:
1. I found creating namespaces outside the e2e tests using `exec.Command` won't fail (because the webhooks are already up then) and creating other resources in the e2e tests also worked. 
2. Therefore, I just tested deleting the `validatingwebhookconfiguration` to disable webhooks and run e2e tests by `go test ./e2e/...` instead of `make local-e2e-test` (with `make kind-deploy` in it before running e2e tests). The namespaces can be created! 

We will need to run the e2e tests after making sure the webhooks are up. I don't have a good idea of how to automate it for now. Will update in the comments.

**Comment by yiqigao217** [comment]
@adrianludwin do you think this is good for @ginnyji to start from or I figure this out and she can start from after this is fixed?

**Comment by adrianludwin** [comment]
Seems like a good one for her to fix, yes!

**Comment by GinnyJI** [comment]
Based on the discussion with Yiqi and Adrian, there are two proposed approaches to this issue:
1. Add a timer in makefile to wait 30s before deploy the e2e test
2. Add BeforeSuite unit in e2e_test.go to check if the webhook  server is ready

I have started implementing the second method, because this solution doesn't reply on the hard 30 seconds time limit. In the event that the webhook is ready in less than 30 seconds, it saves time. And in the event where the webhook takes more than 30 seconds to get ready, it prevents the same failure happening again.

**Comment by adrianludwin** [comment]
+1

**Comment by yiqigao217** [comment]
/assign @GinnyJI 

(Just adding Ginny for the record)
